version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: chatbuds-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INIT DB_DATABASE: chatbuds
      MONGO_INIT DB_ROOT_USERNAME: root
      MONGO_INIT DB_ROOT_PASSWORD: password

  backend:
    build: .
    container_name: chatbuds-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mongo

volumes:
  mongo-data:

